services:
  terrafrom:
    image: hashicorp/terraform:1.6.2
    container_name: terraform
    volumes:
      - ./setup:/tf/setup
      - ./deploy:/tf/deploy
    working_dir: /tf
    environment:
      - AWS_ACESS_KEY_ID=${AWS_ACESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - TF_WORKSPACE={TF_WORKSPACE}
